const PARSE_INT_RADIX = 10;
const ASCENDING_TYPE = 1;
const DESCENDING_TYPE = -1;
const PASSWORD_LENGTH = 10;
const NAME_LENGTH = 3;
const MESSAGE_LENGTH = 6;

module.exports = {
  PARSE_INT_RADIX,
  DESCENDING_TYPE,
  ASCENDING_TYPE,
  PASSWORD_LENGTH,
  NAME_LENGTH,
  MESSAGE_LENGTH,
};